### PR TITLE
Add NCAA cross country demographics

### PR DESCRIPTION
**Pull request by michplunkett**
## What does this PR do?
Add NCAA demographic information for men's and women's cross country from 2014 to 2023.

## How was the functionality tested and verified?
All steps should be completed in the order presented, and you should not move on to the next step until the previous is completed.
- [x] The title of the `html` page is the same as the chart.
- [x] The `meta_data.json` file is filled in correctly (the description is a complete sentence, the title is the same as the visual).
- [x] The chart and its associated pages have been minified using the `npm run process-visual` command.
- [x] The visual is styled similar to other charts (centered title/subtitle, no legends unless absolutely necessary, etc.)
- [x] This visual was approved by the lead developer.
- [x] The visual was approved by the story's stakeholders.

Screenshot 2024-02-02 at 3 25 20 PM

Screenshot 2024-02-02 at 3 25 28 PM

### CODE REVIEW

**Review by asteinhart — COMMENTED** [review]
What exactly is the point being shown here? To me they all look basically the same over time, is that the point? Is a bar chart over time the best visual here?

**Comment by michplunkett** [comment]
I looked at the area chart and that didn't seem particularly useful. Thoughts on a line chart instead? That might give a better and more connected picture.

**Comment by michplunkett** [comment]
The lack of diversity in the space is kind of the goal, yup.

**Comment by michplunkett** [comment]
It was between the bar and line chart:
image

The line chart doesn't give a good side-by-side comparison, so I THINK I'm gonna roll with the bar. The changes aren't significant between each year, but I think there's something to seeing the overall composition of the field each year.

**Comment by michplunkett** [comment]
Gonna make some mods to this tonight.

**Comment by Nik4002** [comment]
Would it be possible to break up the "other" category further? It seems a bit weird to have an "other" category like that when it's so large compared to the "black" category. Also, if possible, you should add a key showing what the three colors mean. Finally, if possible, it might help to make the visuals narrower and taller to accentuate the differences between the bars so they don't all look so similar.

**Comment by michplunkett** [comment]
The `other` category consists of about 5-10 categories that range from visible to very small, this is also how the NCAA presents it. I could give it a shot tho. With regard to the key, I've always been a bit hesitant to use them. I feel like it adds a lot of clutter to the charts that is no longer needed once you scroll over them. With regard to the width of the bars, they are going to be modified so that they compare to the overall NCAA percentages, like this: https://jsfiddle.net/api/post/library/pure/

**Comment by michplunkett** [comment]
We can get the demographics grouped beyond white, black, and other in the overall population of NCAA athletes, but not for each individual sport, unluckly.
Screenshot 2024-02-02 at 1 57 29 PM
Screenshot 2024-02-02 at 1 57 49 PM

**Comment by michplunkett** [comment]
Ready for review, @Nik4002 and @Asteinhart. Running them by Finn as well.

**Pull request merged**
