### PR TITLE
Add 2024 Illinois Election Pie Charts

### PR DESCRIPTION
**Pull request by theaquarium**
## What does this PR do?

Add visuals for the 2024 Illinois Election campaign contribution data.

See screenshots below of each graph:

image

image

image

## How was the functionality tested and verified?
All steps should be completed in the order presented, and you should not move on to the next step until the previous is completed.
- [x] The title of the `html` page is the same as the chart.
- [x] The `meta_data.json` file is filled in correctly (the description is a complete sentence, the title is the same as the visual).
- [x] The chart and its associated pages have been minified using the `npm run process-visual` command.
- [x] The visual is styled similar to other charts (centered title/subtitle, no legends unless absolutely necessary, etc.)
- [ ] This visual was approved by the lead developer.
- [ ] The visual was approved by the story's stakeholders.

### CODE REVIEW

**Comment by notkarenyi** [comment]
image

## How was the functionality tested and verified?
All steps should be completed in the order presented, and you should not move on to the next step until the previous is completed.

- [x] The title of the html page is the same as the chart.
- [x]  The meta_data.json file is filled in correctly (the description is a complete sentence, the title is the same as the visual).
- [x]  The chart and its associated pages have been minified using the npm run process-visual command.
- [x]  The visual is styled similar to other charts (centered title/subtitle, no legends unless absolutely necessary, etc.)
- [ ]  This visual was approved by the lead developer.
- [ ]  The visual was approved by the story's stakeholders.

**Comment by notkarenyi** [comment]
need advice on the title/subtitle, i am not so good at writing those. for example is it true that these are total campaign funds or only donations

**Comment by Nik4002** [comment]
@notkarenyi Yeah, I would change the title to say "total donations". Also, regarding the subtitle, I'm inclined to say you should just remove it or change it to something like "These three candidates raised a total of $_____." (also make sure it's a full sentence per our style guide). Looking at the draft of the article (I believe I sent you a link in our email chain), it doesn't seem like they're making any specific claims about the total data, so it's not necessary to call attention to Robert Peters's numbers. Otherwise, it looks great!

@theaquarium Thanks! Austin had a few comments that I'll paraphrase now:
- You should remove the cent values from the subtitles, especially because they're zero anyway.
- Be careful with the color scheme when making a piece on politics. To avoid the "red = R, blue = D" association, I'd recommend removing the blue color from the color scheme.

Thanks, both of you!!

**Comment by notkarenyi** [comment]
done! @Nik4002 

image

**Comment by theaquarium** [comment]
> * You should remove the cent values from the subtitles, especially because they're zero anyway.
> * Be careful with the color scheme when making a piece on politics. To avoid the "red = R, blue = D" association, I'd recommend removing the blue color from the color scheme.

Done!

image
image
image

**Review by Nik4002 — APPROVED** [review]
Looks great!

**Pull request merged**
