### PR TITLE
Create second-draft graphics for Common Data Set story

### PR DESCRIPTION
**Pull request by air-kyi**
## What does this PR do?
- Bar chart for class of '28 race distribution
- Dumbbell chart for change in overall undergraduate race distribution from 2012-2022
- Line chart for change in gender distribution for admitted students 2012-2023. 2 options for this with different calculation methods
  - method 1: numerator=women admitted, denominator=women applied. this shows that less women were admitted than men consistently every year since 2012. however, more women have applied every year since 2012 than men. 
  - method 2: controlling for number of people applying per group. numerator=women admitted. denominator=ALL applicants. this shows that more women were admitted than men in 2016 but even proportional to the student body as a whole, more men were admitted most years. I think this is a more condemning conclusion but more complex than 1.

## How was the functionality tested and verified?
All steps should be completed in the order presented, and you should not move on to the next step until the previous is completed.
- [x] The title of the `html` page is the same as the chart.
- [x] The `meta_data.json` file is filled in correctly (the description is a complete sentence, the title is the same as the visual).
- [x] The chart and its associated pages have been minified using the `npm run process-visual` command.
- [x] The visual is styled similar to other charts (centered title/subtitle, no legends unless absolutely necessary, etc.)
- [x] This visual was approved by the lead developer.
- [x] The visual was approved by the story's stakeholders.

image

image

image

### CODE REVIEW

**Comment by air-kyi** [comment]
linting checks will pass after other PR merged

**Comment by air-kyi** [comment]
also need help on the titles plsss I am not amazing at catchy phrases

**Comment by air-kyi** [comment]
@asteinhart updates done! 
> dumbell chart comments
> - i think maybe we take out all the three that are basically 1%, we already say it in the text

keeping it for now - same as w the bar chart, I think that 1) visuals should be redundant to the text because many people skim or skip the text and only look at visuals, and 2) if I were American Indian/Pacific Islander I would be interested that there were no/1 native students enrolled at UChicago

> - can we put them in order of the change with White on top?

the absolute magnitude of change or just the number?

> - then can we just annotate the chart so the first one has in black text "2012 Share" and in blue "2022 Share". and then remove legend
> - We have 2023 numbers right? can we use these
> - can we try a dif color, like the dark green maybe (#58593F) and make the line connecting darker?

the dark green is too dark:( not enough contrast w the black to tell. if u want we can use that but use a different shape as the marker, eg square

> -  this data is not just undergrads though right?

oh in that case we can't use 2023 numbers, those are undergrad only

> bar chart comments:
> - i think maybe the x axis makes more sense as share of class rather than abs number?
> - can we take the smallest three categories and add an Other maybe? the zeros kinda seem odd to me

same as above for dumbbell

> - i think this is makeup of the whole undergraduate in the 23-24 school year, not just class of 28?

I used the first time first year column

> gender line comment
> - hmm i think method two is a little too complex, but maybe worth incorporating in the text?
> - for method 1 can we remove point label for all the series, make the overall the maroon color (#80000) and thicker line?

image
image
image

**Comment by air-kyi** [comment]
discussed revisions
- [x] remove the source
- [x] remove legend in gender and move to series label
- [x] gender dashed lines? 1 point thinner
- [x] group native groups dumbbell
- [x] dumbbell 2 different colors, gray connecting thick, transparent
- [x] use id for annotation for dumbbell
- [x] order by magnitude or 2012
- [x] change race bar to whole body
- [x] add % label to race and change to share of all students

**Comment by air-kyi** [comment]
image
image
image

**Comment by asteinhart** [comment]
gtg, waiting on any edits from copy on chart titles then will re format, minify and merge! cc @air-kyi

**Review by asteinhart — APPROVED** [review]
lgtm!

**Pull request merged**
